### ISSUE TITLE
no database

### ISSUE THREAD

**Issue by quintendc** [ra1han/aspnet-core-identity#1]
when I build the database with “dotnet ef database update” I don’t see the database in my SSMS.
I can register and login without problem but any idea why the database won’t show up?

**Comment by ra1han** [comment]
In the appsettings.json file you have a connection string. Hi can you please confirm that you are connecting to the right DB server according to this connection string?

**Comment by quintendc** [comment]
this is the connectionString: 

{
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\MSSQLLocalDB;Database=IdentityDemo;Trusted_Connection=True;MultipleActiveResultSets=true"
 },

**Comment by ra1han** [comment]
My question was, can you confirm that you are connecting to this DB instance - (localdb)\MSSQLLocalDB? Can you post a picture of SSMS after connecting to the DB?

**Comment by quintendc** [comment]
Ok sorry i was wrong, now i see the database. 

thanks
